[package]
name = "lean-sys"
version.workspace = true
edition.workspace = true

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true }
elan = { workspace = true }
elan-dist = { workspace = true }
